### ISSUE TITLE
Make bigger font

### ISSUE THREAD

**Issue by sigrlami** [odhug/odhac-badges#1]
Make bigger font for Name

**Comment by sigrlami** [comment]
Current size is optimal for names, because long name, like `Woldemar von Voigt`, will naturally split into 2 lines. I can place name and surname on separate lines, but due to different sizes it's not always look good, specially for short names.

@feuerbach, should I make bigger font for nicknames too?

**Comment by UnkindPartition** [comment]
Looks good so far. I'll play with sizes when I know the actual badge size.

Thanks!
